---
- name: Copy default html file for Apache servers
  hosts: all
  become: true
  tasks:
    - name: Copy default html file
      tags: copy
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
      when: ansible_distribution == "Ubuntu"
