---

- hosts: all
  become: true
  tasks:

  - name: update repo index and install apache2 and libapache2-mod-php package
    apt: 
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
