---
- hosts: all
  become: true
  pre_tasks:
    - name: update repo index
      tags: update
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: install apache2 and php for Ubuntu servers
      tags: apache,php
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: absent
      when: ansible_distribution == "Ubuntu"
