---

- hosts: all
  become: true
  pre_tasks:
  - name: update repo index 
    tags: update 
    apt: e
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  - name: install apache2 and libapache2-mod-php package
    tags: apache,php
    apt: 
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
    when: ansible_distribution == "Ubuntu"
