---
- hosts: all
  become: true
  pre_tasks:
    - name: update repo index 
      tags: update 
      apt: 
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks:
    - name: install apache2 and php for Ubuntu servers
      tags: apache, php
      apt: 
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"
    - name: copy default html file for site
      tags: apache, apache2, httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
- hosts: db_server
  become: true
  tasks:
    - name: install mysql-server for Ubuntu servers
      tags: mysql
      apt: 
        name: mysql-server
        state: latest
      when: ansible_distribution == "Ubuntu"
    
- hosts: web_server
  become: true
  tasks:
    - name: install unzip
      tags: terraform
      package:
        name: unzip

    - name: download terraform binary zip
      tags: terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/1.1.4/terraform_1.1.4_linux_amd64.zip
        dest: /tmp/terraform.zip
        mode: '0644'

    - name: unzip terraform binary
      tags: terraform
      unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin/
        remote_src: yes
        mode: '0755'
        owner: root
        group: root 

    