---
- name: Update apt on Ubuntu servers
  hosts: all
  become: true
  pre_tasks:
    - name: Update apt 
      tags: update
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
